# Generated by Django 3.2.12 on 2022-03-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_teacher_subject_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_subject',
            old_name='subject_teacher_id',
            new_name='teach_id',
        ),
        migrations.AddField(
            model_name='teacher_subject',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='teacher_subject',
            table='teachers_subjects',
        ),
    ]
